package com.createpro.customerapp.model

enum class TYPE {
    DOUBLE,STRING
}

enum class CustomerSourceEnum(val pos: Int, val type: TYPE)   {
    COMPANY_CODE(0, TYPE.DOUBLE),
    KANJI_TRADE_NAME(1, TYPE.STRING),
    SEARCH_KANA_TRADE_NAME(2, TYPE.STRING),
    KANJI_TRADE_NAMES_FOR_SEARCH(3, TYPE.STRING),
    COMPANY_PHONE(4, TYPE.STRING),
    REPRESENTATIVE_NAME(5, TYPE.STRING),
    REPRESENTATIVE_KANA_NAME(6, TYPE.STRING),
    TDB_INDUSTORY_CLASSIFICATION_NAME_PRINCIPAL_INDUSTRY(7, TYPE.STRING),
    TDB_INDUSTRY_CLASSIFICATION_NAME_EMPLOYEE(8, TYPE.STRING),
    POSTAL_CODE_NUMBER(9, TYPE.DOUBLE,),
    COMPANY_LOCATION_BARCODE_NUMBER(10, TYPE.STRING),
    IMPERIAL_ADDRESS_CODE(11, TYPE.DOUBLE),
    KANJI_ADDRESS(12, TYPE.STRING),
    CAPITAL_THOUSAND_YEN(13, TYPE.DOUBLE),
    NUMBER_OF_EMPLOYEES(14, TYPE.DOUBLE),
    YEAR_OF_FOUNDATION(15, TYPE.DOUBLE),
    MONTH_OF_FOUNDATION(16, TYPE.DOUBLE),
    YEAR_ESTABLISHED(17, TYPE.DOUBLE,),
    MONTH_OF_ESTABLISHMENT(18, TYPE.DOUBLE),
    FISCAL_YEAR(19, TYPE.DOUBLE),
    FISCAL_MONTH(20, TYPE.DOUBLE),
    NET_SALES_MILLIONS_OF_YEN(21, TYPE.DOUBLE),
    UPDATE_DATE(22, TYPE.STRING)
}

fun getSource(index: Int):String =
    CustomerSourceEnum.values().first { index == it.pos }.toString()